### ISSUE TITLE
Tabs get added after META tab

### ISSUE THREAD

**Issue by eduardomart** [SahAssar/bolt-editcontentcustomtabs#3]
Per our conversation in Slack, the *meta* tab, should always be the last tab.
But it's not always the case, here's a sample `contenttype` added to a clean install with dummy content:

```
repertoire:
    name: Productions
    singular_name: Production
    default_status: publish
    sort: -datepublish
    listing_sort: -datepublish
    title_format: [ title ]
    relations:
        pages:
            multiple: true
            label: "Select pages"
            format: '{{ item.title }}'
            group: PAGES-TEST    
    fields:
        title:
            type: text
            class: large
            group: About
            required: true
        composer:
            type: text
        about:
            type: html
            label: About
            height: 200
        image:
            type: image
            label: Cover image
        doublebill:
            type: select
            label: Double Bill
            multiple: false
            values: repertoire/title
        productions:
            type: repeater
            label: Productions
            group: Production Credits
            fields:
                company:
                    type: select
                    label: Company
                    values: companies/title
                    sort: title
                    autocomplete: true
                    required: true
                year:
                    type: text
                    label: Year
                    variant: inline
                cast:
                    type: html
                    label: Artists
                    height: 200
                gallery:
                    type: imagelist
                    label: Photos
                photographer:
                    type: text
                    label: Photographer
                    variant: inline
        slug:
            type: slug
            uses: title
            group: meta
```

Creates the following:
![2017-03-01 15-30-19](https://cloud.githubusercontent.com/assets/1833020/23486263/0e542dae-fe94-11e6-8070-7011239224bd.png)

Relevant versions:
Bolt 3.2.7
PHP 7.0
Editcontentcustomtabs 1.1.0
